name: ci

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.3.0
        with:
          dotnet-version: |
            8.0.x
            10.0.x

      - name: Restore
        run: dotnet restore FluxFlow.sln

      - name: Build
        run: dotnet build FluxFlow.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test FluxFlow.sln --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"
